from embeddings import get_embedding
from qdrant_db import client, COLLECTION
import requests


def rerank(query, hits):
    q_words = set(query.lower().split())
    return sorted(
        hits,
        key=lambda h: len(q_words & set(h.payload["content"].lower().split())),
        reverse=True
    )

def detect_intent(query):
    q = query.lower()

    if "code" in q or "example" in q:
        return {"type": "code"}
    if "explain" in q or "what is" in q:
        return {"type": "mixed"}
    return {}

def ask(query):
    vec = get_embedding(query)
    intent = detect_intent(query)

    filters = []
    if "type" in intent:
        filters.append({"key": "type", "match": {"value": intent["type"]}})

    hits = client.search(
    collection_name=COLLECTION,
    query_vector=vec,
    limit=10,
    query_filter={
        "should": [
            {"key": "content", "match": {"text": query}},
            *filters
            ]
        }
    )

    hits = rerank(query, hits)[:4]


    context = ""
    for h in hits:
        block = f"\n[Doc: {h.payload['doc']} | Section: {h.payload['heading']}]\n"
        if h.payload["type"] == "code":
            block += f"```{h.payload['language']}\n{h.payload['content']}\n```"
        else:
            block += h.payload["content"]

        context += block + "\n\n"

    prompt = f"""
            You are a Qdrant documentation assistant.
            Answer strictly using the context below.

            If the answer is not present, reply:
            "I could not find this in the Qdrant documentation."

            Context:
            {context}

            Question:
            {query}
"""

    res = requests.post("http://localhost:11434/api/chat", json={
    "model": "llama3",
    "messages": [
        {"role": "system", "content": "You are a Qdrant documentation assistant."},
        {"role": "user", "content": prompt}
    ],
    "stream": False
    })


    data = res.json()

    if "response" in data:
        return data["response"]

    if "message" in data:
        return data["message"]["content"]

    return "No response generated by model."
